import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar';
import SearchBar from './components/SearchBar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className='flex'>
          <div className='basis-1/4 shadow-[2px_0_5px_rgba(0,0,0,0.1)]'>
            <Navbar />
          </div>
          <main className='basis-3/4 bg-[#EDEDED] p-10'>
            <SearchBar />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
